version: "3.3"

services:
  api:
    image: joaofnfernandes/api
    #build:
    #  context: api
    #  args:
    #    - "APP=api"
    ports:
      - "8000:8000"

  msgq:
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    hostname: messagequeue
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    ports: # only needed for local development
      - "5672:5672" # amqp without TLS
      - "15672:15672" ## admin UI, and HTTP API
