version: "3.3"

services:
  api:
    image: joaofnfernandes/api
    build:
      dockerfile: api.Dockerfile
      context: .
    #  args:
    #    - "APP=api"
    environment:
      MQ_USER: admin
      MQ_PASS: password
      MQ_HOST: msgq
      MQ_PORT: 5672
      MQ_PROTOCOL: amqp
      API_NETWORK: 0.0.0.0
      API_PORT: 8000
    ports:
      - "8000:8000"

#  agent:
#    image: joaofnfernandes/agent
#    build: ./agent

  msgq:
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    hostname: messagequeue
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    ports: # only needed for local development
      - "5672:5672" # amqp without TLS
      - "15672:15672" ## admin UI, and HTTP API
